In [1]:
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

In [3]:
D = np.array([
    [1 ,3, 3],
    [2, 3, 1],
    [2, 2, 3]
])
D

array([[1, 3, 3],
       [2, 3, 1],
       [2, 2, 3]])

In [4]:
DT1 = np.transpose(D)

In [5]:
DT2 = D.T

In [6]:
np.array_equiv(DT1, DT2)

True

In [7]:
O = np.array([
    [2,3,-1,-3],
    [1,3,2,-3],
])
O.shape

(2, 4)

In [8]:
np.transpose(O).shape

(4, 2)

In [9]:
O.T.shape

(4, 2)

## Dot Product/Inner Product

In [10]:
D = np.array([
    [2,3],
    [0,3]
])
O = np.array([
    [3,3],
    [3,2]
])

In [11]:
np.dot(D,O)

array([[15, 12],
       [ 9,  6]])

In [12]:
D.dot(O)

array([[15, 12],
       [ 9,  6]])

In [13]:
D @ O 

array([[15, 12],
       [ 9,  6]])

In [15]:
np.matmul(D,O)

array([[15, 12],
       [ 9,  6]])

## Rule 1 The inner dimensions of the two matrices in question must be the same.

In [16]:
D = np.array([
    [2,3],
    [3,1],
    [0,1]
])
O = np.array([
    [1,1],
    [3,2],
    [0,3]
])
N = np.array([
    [0,3,2],
    [1,1,3]
])
print(D.shape)
print(O.shape)
print(N.shape)

(3, 2)
(3, 2)
(2, 3)


In [17]:
D @ N

array([[ 3,  9, 13],
       [ 1, 10,  9],
       [ 1,  1,  3]])

In [18]:
O @ N

array([[ 1,  4,  5],
       [ 2, 11, 12],
       [ 3,  3,  9]])

In [20]:
D @ O.T

array([[ 5, 12,  9],
       [ 4, 11,  3],
       [ 1,  2,  3]])

In [21]:
D = np.array([
    [1,3,4,2]
])
O = np.array([
    [2,3,1,-3]
])
print(D.shape)
print(O.shape)

(1, 4)
(1, 4)


In [22]:
O.T @ D

array([[  2,   6,   8,   4],
       [  3,   9,  12,   6],
       [  1,   3,   4,   2],
       [ -3,  -9, -12,  -6]])

## Rule 2: Dot Product has special properties

In [23]:
D = np.array([
    [3,1,2],
    [-3,-2,-1],
    [3,2,3]
])
O = np.array([
    [3,2,3],
    [2,2,1],
    [1,1,3]
])
N = np.array([
    [-3,-2,-3],
    [2,3,2],
    [1,1,3]
])

In [24]:
D.dot(np.zeros(D.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
z_mat = np.zeros(D.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
a_dot_z = D.dot(np.zeros(D.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.array_equal(a_dot_z,z_mat)

True

In [29]:
null_mat = np.empty(D.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Determinant

In [30]:
D = np.array([
    [3,1],
    [0,2]
])
np.linalg.det(D)

6.0

In [31]:
O = np.array([
    [1,3,2,3],
    [-1,2,3,3],
    [-3,-2,-3,-3],
    [1,3,2,3]
])
np.linalg.det(O)

0.0

## Inverse

In [32]:
D = np.array([
    [1,3],
    [3,2]
])

np.array(D @ np.linalg.inv(D), dtype=int)

array([[0, 0],
       [0, 0]])

In [34]:
O = np.array([
    [1,3,2,1,3,2,3],
    [0,1,0,3,2,3,2],
    [2,2,1,0,0,0,3],
    [1,2,2,2,2,3,1],
    [1,2,3,3,1,1,1],
    [-3,3,1,0,0,3,-3],
    [-2,-3,1,2,1,2,1],
])
O_inv = np.linalg.inv(O)
np.array(O @ O_inv,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])